apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repos.yaml
  - traefik.yaml
  - cert-manager.yaml
  - external-dns.yaml
configMapGenerator:
  - name: traefik-values
    namespace: flux-system
    files:
      - values.yaml=../../../traefik/values.yaml
generatorOptions:
  disableNameSuffixHash: true
