# SOPS Configuration for Encrypted Secrets
# This file configures SOPS to use age encryption for secrets

# Creation rules - how to encrypt new files
creation_rules:
  # Central config file (contains WiFi passwords, etc.)
  - path_regex: ^config\.yaml$
    encrypted_regex: "^(password|secret|key|token)$"
    age: "age19grykgll3ugdtt0z98p4j0qefrt6alqesnwsw7gwj8kteamt2swslppqtc"
  # Encrypt all secrets in the secrets directory
  - path_regex: secrets/.*\.yaml$
    age: "age19grykgll3ugdtt0z98p4j0qefrt6alqesnwsw7gwj8kteamt2swslppqtc"
  # Encrypt Kubernetes secrets
  - path_regex: .*secret.*\.yaml$
    encrypted_regex: "^(data|stringData)$"
    age: "age19grykgll3ugdtt0z98p4j0qefrt6alqesnwsw7gwj8kteamt2swslppqtc"
  # Encrypt .env files
  - path_regex: .*\.env$
    age: "age19grykgll3ugdtt0z98p4j0qefrt6alqesnwsw7gwj8kteamt2swslppqtc"
# Note: Store your private key (key.txt) securely and NEVER commit it
# Export the key location: export SOPS_AGE_KEY_FILE=~/.sops/key.txt
