---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
  comments:
    require-starting-space: true
    min-spaces-from-content: 1
  indentation:
    spaces: 2
    indent-sequences: true
  document-start: disable
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

ignore:
  - '.git/'
  - 'secrets/*.enc.yaml'
