apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - home-assistant.yaml
  - companion.yaml
  - nodered.yaml
  - zigbee2mqtt.yaml
  - esphome.yaml
  - code-server.yaml
  - influxdb.yaml
