# KIND cluster configuration for local Mac development
# Simulates a multi-node cluster for testing
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kube-world

# Configure nodes
nodes:
  # Control plane node
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true,node.kubernetes.io/role=control-plane"
    extraPortMappings:
      # HTTP
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      # HTTPS  
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      # NodePort range for services
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP
      - containerPort: 30001
        hostPort: 30001
        protocol: TCP

  # Worker node 1 - simulates Pi/edge device
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node.kubernetes.io/role=worker,topology.kubernetes.io/zone=edge,workload-type=iot"
    extraMounts:
      # Mount for persistent storage testing
      - hostPath: /tmp/kube-world/pv1
        containerPath: /data/pv1

  # Worker node 2 - simulates general compute
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node.kubernetes.io/role=worker,topology.kubernetes.io/zone=local,workload-type=general"
    extraMounts:
      - hostPath: /tmp/kube-world/pv2
        containerPath: /data/pv2

# Networking configuration
networking:
  # Use default CNI (kindnet)
  disableDefaultCNI: false
  # Pod subnet
  podSubnet: "10.244.0.0/16"
  # Service subnet
  serviceSubnet: "10.96.0.0/12"
  # API server address
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443

# Feature gates for testing
featureGates:
  # Enable topology-aware hints for traffic routing
  TopologyAwareHints: true

# Container registry mirrors (optional, speeds up pulls)
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
      endpoint = ["https://registry-1.docker.io"]
