# Hardware Inventory for kube-world
# Central registry of all hardware devices in the cluster
# This file is used by Ansible, cloud-init, and Kubernetes for device management

---
# Schema version for future compatibility
apiVersion: kube-world.io/v1
kind: HardwareInventory
metadata:
  name: kube-world-inventory
  lastUpdated: "2026-01-16"

#===============================================================================
# Compute Nodes
#===============================================================================
nodes:
  # Primary development machine
  - id: macbook-pro-m3
    name: "MacBook Pro 16-inch (2024)"
    type: development
    role: management
    enabled: true
    hardware:
      manufacturer: Apple
      model: "MacBook Pro 16-inch"
      cpu:
        model: "Apple M3 Max"
        architecture: arm64
        cores: 14  # 10 performance + 4 efficiency
        threads: 14
      memory:
        total: 32GB
        type: unified
      storage:
        - type: nvme
          size: 1TB
          device: /dev/disk0
      gpu:
        model: "Apple M3 Max GPU"
        cores: 30
    network:
      interfaces:
        - name: en0
          type: wifi
          mac: "60:3e:5f:64:df:21"  # Update with actual
        - name: en9
          type: thunderbolt
          mac: "6c:1f:f7:56:fa:3a"
        - name: en8
          type: thunderbolt
          mac: "20:7b:d2:24:33:8e"
    capabilities:
      - docker
      - kind
      - development
    labels:
      node.kubernetes.io/role: management
      topology.kubernetes.io/zone: local
      workload-type: development

  # Primary edge device
  - id: pi5-master-1
    name: "Raspberry Pi 5 - Master"
    type: edge
    role: master
    enabled: true
    hardware:
      manufacturer: Raspberry Pi Foundation
      model: "Raspberry Pi 5"
      cpu:
        model: "Broadcom BCM2712"
        architecture: arm64
        cores: 4
        threads: 4
        frequency: 2.4GHz
      memory:
        total: 16GB
        type: LPDDR4X
      storage:
        - type: microsd
          size: 64GB
          device: /dev/mmcblk0
        # M.2 expansion (when added)
        # - type: nvme
        #   size: 500GB
        #   device: /dev/nvme0n1
    network:
      interfaces:
        - name: eth0
          type: ethernet
          mac: "XX:XX:XX:XX:XX:XX"  # Update with actual
          ip: 192.168.1.100  # Target static IP
        - name: wlan0
          type: wifi
          mac: "XX:XX:XX:XX:XX:XX"
    capabilities:
      - k3s
      - usb-passthrough
      - gpio
      - bluetooth
    labels:
      node.kubernetes.io/role: master
      topology.kubernetes.io/zone: edge
      workload-type: iot
      hardware: raspberry-pi-5
    # NVMe Configuration for boot (when M.2 HAT added)
    # config:
    #   boot:
    #     order: "0xf416"  # NVMe first, then SD
    #     nvme:
    #       pcie_gen: 3

#===============================================================================
# IoT Devices and Controllers
#===============================================================================
iot_devices:
  # Zigbee Controller
  - id: zigbee-controller-1
    name: "Zigbee USB Controller"
    type: zigbee
    status: planned  # Change to 'active' when purchased
    assignedNode: pi5-master-1
    hardware:
      # Example: Sonoff Zigbee 3.0 USB Dongle Plus
      manufacturer: TBD  # Update when purchased
      model: TBD
      protocol: zigbee
      version: "3.0"
      usb:
        vendorId: "XXXX"   # Update with actual
        productId: "XXXX"
        devicePath: /dev/ttyUSB0
    udevRule: |
      SUBSYSTEM=="tty", ATTRS{idVendor}=="XXXX", ATTRS{idProduct}=="XXXX", SYMLINK+="zigbee", MODE="0666", GROUP="dialout"
    homeAssistant:
      integration: zha  # or zigbee2mqtt
      config:
        device: /dev/zigbee

  # Z-Wave Controller (future)
  - id: zwave-controller-1
    name: "Z-Wave USB Controller"
    type: zwave
    status: planned  # For HA Connect ZWA-2
    assignedNode: pi5-master-1
    hardware:
      manufacturer: Nabu Casa
      model: "Home Assistant Connect ZWA-2"
      protocol: zwave
      version: "700"
      usb:
        vendorId: "10c4"
        productId: "ea60"
        devicePath: /dev/ttyACM0
    udevRule: |
      SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", SYMLINK+="zwave", MODE="0666", GROUP="dialout"
    homeAssistant:
      integration: zwave_js
      config:
        device: /dev/zwave

  # Thread/Matter Controller (future)
  - id: thread-controller-1
    name: "Thread Border Router"
    type: thread
    status: planned  # For HA Connect ZBT-2
    assignedNode: pi5-master-1
    hardware:
      manufacturer: Nabu Casa
      model: "Home Assistant Connect ZBT-2"
      protocol: thread
      version: "1.3"
      usb:
        vendorId: "XXXX"
        productId: "XXXX"
        devicePath: /dev/ttyACM1
    homeAssistant:
      integration: thread
      config:
        border_router: true

#===============================================================================
# Network Infrastructure
#===============================================================================
network:
  # Home network configuration
  - id: home-network
    name: "Home Network"
    type: lan
    config:
      subnet: 192.168.1.0/24
      gateway: 192.168.1.1
      dns:
        - 8.8.8.8
        - 8.8.4.4
      dhcp:
        range: 192.168.1.50-192.168.1.199
        # Static reservations (configure in router)
        reservations:
          - hostname: pi5-master-1
            mac: "XX:XX:XX:XX:XX:XX"
            ip: 192.168.1.100

#===============================================================================
# Cloud Resources (Future)
#===============================================================================
cloud_resources: []
# Future: Add cloud VMs, managed K8s clusters, etc.
# - id: aws-eks-prod
#   name: "EKS Production Cluster"
#   provider: aws
#   type: managed-kubernetes
#   region: us-east-1
#   ...

#===============================================================================
# Metadata
#===============================================================================
metadata:
  # Inventory generation settings
  auto_discover: false  # Future: Enable auto-discovery
  
  # Validation settings
  validation:
    required_fields:
      nodes: [id, name, type, hardware.cpu.architecture]
      iot_devices: [id, name, type, assignedNode]
  
  # Sync settings for GitOps
  gitops:
    sync_interval: 5m
    auto_apply_udev: true
