#!/usr/bin/env bash
# Install tv-bridge as a systemd service on a vanilla Pi (Saitama-style
# Companion installs, or any host that doesn't run k3s). Idempotent —
# re-run after `git pull` to refresh the script.
#
# Usage:
#     sudo ./install.sh <TV_HOST_IP_OR_HOST:PORT>
#
# Example:
#     sudo ./install.sh 192.168.10.20:5555
#
# After install, pair ADB once (the unit reads adb keys from
# /var/lib/tv-bridge/.android):
#     sudo -u tv-bridge HOME=/var/lib/tv-bridge adb pair <TV_IP>:<PAIR_PORT> <CODE>
#     sudo -u tv-bridge HOME=/var/lib/tv-bridge adb connect <TV_IP>:5555
#     sudo systemctl restart tv-bridge

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "must run as root (sudo)" >&2
    exit 1
fi

TV_HOST="${1:-}"
if [[ -z "$TV_HOST" ]]; then
    echo "usage: $0 <TV_HOST:PORT>" >&2
    exit 2
fi

# 1. dependencies
DEBIAN_FRONTEND=noninteractive apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    android-tools-adb python3

# 2. user + state dir
if ! id tv-bridge >/dev/null 2>&1; then
    useradd --system --home-dir /var/lib/tv-bridge --shell /usr/sbin/nologin tv-bridge
fi
install -d -o tv-bridge -g tv-bridge -m 0750 /var/lib/tv-bridge

# 3. install script + systemd unit
SRC_DIR="$(cd "$(dirname "$0")/.." && pwd)"
install -d -m 0755 /opt/tv-bridge
install -m 0755 "$SRC_DIR/bridge.py" /opt/tv-bridge/bridge.py

cat > /etc/default/tv-bridge <<EOF
# tv-bridge environment — generated by install.sh on $(date -u +%FT%TZ)
TV_HOST=$TV_HOST
LISTEN_ADDR=127.0.0.1:9990
EOF
chmod 0644 /etc/default/tv-bridge

install -m 0644 "$SRC_DIR/vanilla/tv-bridge.service" /etc/systemd/system/tv-bridge.service

# 4. enable + start
systemctl daemon-reload
systemctl enable --now tv-bridge.service
systemctl status tv-bridge.service --no-pager | head -20 || true

cat <<EOF

tv-bridge installed.
  Endpoint:  http://127.0.0.1:9990
  TV_HOST:   $TV_HOST
  Logs:      journalctl -u tv-bridge -f

Pair ADB (one-time, after enabling Wireless debugging on the TV):
  sudo -u tv-bridge HOME=/var/lib/tv-bridge adb pair <TV_IP>:<PAIR_PORT> <CODE>
  sudo -u tv-bridge HOME=/var/lib/tv-bridge adb connect $TV_HOST
  sudo systemctl restart tv-bridge

Health check:
  curl -s http://127.0.0.1:9990/healthz
EOF
